name: 'BD Class Check'
description: 'Updates CSS class names based on BetterDiscord changes list and creates a PR'
author: 'Your Name'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  files:
    description: 'Comma-separated list of file paths or glob patterns (e.g., "src/**/*.css,styles/*.css")'
    required: true
    default: 'src/**/*.css'
  
  changes-url:
    description: 'URL to the Changes.txt file'
    required: false
    default: 'https://raw.githubusercontent.com/SyndiShanX/Update-Classes/refs/heads/main/Changes.txt'
  
  github-token:
    description: 'GitHub token for creating PRs'
    required: true
    default: ${{ github.token }}
  
  branch-name:
    description: 'Branch name for the PR'
    required: false
    default: 'css-class-updates'
  
  commit-message:
    description: 'Commit message template'
    required: false
    default: 'chore: update CSS classes'
  
  pr-title:
    description: 'Pull request title'
    required: false
    default: 'chore: Update CSS classes from upstream changes'
  
  pr-labels:
    description: 'Comma-separated list of labels for the PR'
    required: false
    default: 'dependencies,automated'

outputs:
  has-changes:
    description: 'Whether any changes were made'
    value: ${{ steps.update.outputs.has_changes }}
  
  total-changes:
    description: 'Total number of class changes made'
    value: ${{ steps.summary.outputs.total_changes }}
  
  modified-files:
    description: 'Number of files modified'
    value: ${{ steps.summary.outputs.modified_files }}
  
  pr-number:
    description: 'Pull request number (if created)'
    value: ${{ steps.create-pr.outputs.pull-request-number }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        echo "📦 Installing dependencies..."
        
        if [ ! -d "node_modules" ] || [ ! -f "node_modules/glob/package.json" ]; then
          npm ci
          echo "✓ Dependencies installed"
        else
          echo "✓ Dependencies already present"
        fi
    
    - name: Get Changes.txt commit date
      id: changes_date
      shell: bash
      run: |
        CHANGES_URL="${{ inputs.changes-url }}"
        
        # Parse GitHub URL to get API endpoint
        if [[ $CHANGES_URL =~ github\.com/([^/]+)/([^/]+)/.*/(main|master)/Changes\.txt ]]; then
          OWNER="${BASH_REMATCH[1]}"
          REPO="${BASH_REMATCH[2]}"
          BRANCH="${BASH_REMATCH[3]}"
          
          # Get the commit date from GitHub API
          COMMIT_DATE=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/commits?path=Changes.txt&sha=$BRANCH&per_page=1" | jq -r '.[0].commit.committer.date')
          echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
          echo "Changes.txt last updated: $COMMIT_DATE"
        else
          echo "commit_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
        fi
    
    - name: Run CSS class update script
      id: update
      shell: bash
      run: |
        export CHANGES_URL="${{ inputs.changes-url }}"
        export FILES_INPUT="${{ inputs.files }}"
        
        echo "🔄 Running CSS class update..."
        echo "Changes URL: $CHANGES_URL"
        echo "Files pattern: $FILES_INPUT"
        
        if node update-classes.js; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "✓ Changes detected and applied"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "✓ No changes needed"
        fi
    
    - name: Read summary
      id: summary
      if: steps.update.outputs.has_changes == 'true'
      shell: bash
      run: |
        TOTAL=$(jq -r '.totalChanges' changes-summary.json)
        FILES=$(jq -r '.modifiedFiles | length' changes-summary.json)
        echo "total_changes=$TOTAL" >> $GITHUB_OUTPUT
        echo "modified_files=$FILES" >> $GITHUB_OUTPUT
    
    - name: Generate PR body
      if: steps.update.outputs.has_changes == 'true'
      shell: bash
      run: |
        COMMIT_DATE="${{ steps.changes_date.outputs.commit_date }}"
        
        cat << 'EOF' > pr-body.md
        ## CSS Class Updates
        
        This PR updates CSS classes based on changes from the upstream Changes.txt file.
        
        **Changes.txt last updated:** COMMIT_DATE_PLACEHOLDER
        
        ### Summary
        EOF
        
        sed -i "s/COMMIT_DATE_PLACEHOLDER/$COMMIT_DATE/" pr-body.md
        
        # Add summary from JSON
        node -e "
          const summary = require('./changes-summary.json');
          console.log(\`\n**Total changes:** \${summary.totalChanges}\`);
          console.log(\`**Files modified:** \${summary.modifiedFiles.length}\n\`);
          console.log(\`### Modified Files\n\`);
          summary.modifiedFiles.forEach(file => console.log(\`- \${file}\`));
          console.log(\`\n### Changes Detail\n\`);
          const grouped = {};
          summary.changes.forEach(change => {
            if (!grouped[change.file]) grouped[change.file] = [];
            grouped[change.file].push(change);
          });
          Object.entries(grouped).forEach(([file, changes]) => {
            console.log(\`\n#### \${file}\n\`);
            changes.slice(0, 50).forEach(change => {
              console.log(\`- Line \${change.line}: \\\`.\${change.oldClass}\\\` → \\\`.\${change.newClass}\\\`\`);
            });
            if (changes.length > 50) {
              console.log(\`\n_... and \${changes.length - 50} more changes_\`);
            }
          });
        " >> pr-body.md
    
    - name: Create Pull Request
      id: create-pr
      if: steps.update.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github-token }}
        commit-message: |
          ${{ inputs.commit-message }}
          
          Changes based on updates from ${{ steps.changes_date.outputs.commit_date }}
        branch: ${{ inputs.branch-name }}
        delete-branch: true
        title: ${{ inputs.pr-title }}
        body-path: pr-body.md
        labels: ${{ inputs.pr-labels }}
