name: 'BD Class Check'
description: 'Updates CSS class names based on BetterDiscord changes list and creates a PR'
author: 'Your Name'

branding:
  icon: 'refresh-cw'
  color: 'blue'

inputs:
  files:
    description: 'Comma-separated list of file paths or glob patterns (e.g., "src/**/*.css,styles/*.css")'
    required: true
    default: 'src/**/*.css'
  
  changes-url:
    description: 'URL to the Changes.txt file'
    required: false
    default: 'https://raw.githubusercontent.com/SyndiShanX/Update-Classes/refs/heads/main/Changes.txt'
  
  github-token:
    description: 'GitHub token for creating PRs'
    required: true
  
  branch-name:
    description: 'Branch name for the PR'
    required: false
    default: 'css-class-updates'
  
  commit-message:
    description: 'Commit message template'
    required: false
    default: 'chore: update CSS classes'
  
  pr-title:
    description: 'Pull request title'
    required: false
    default: 'chore: Update CSS classes from upstream changes'
  
  pr-labels:
    description: 'Comma-separated list of labels for the PR'
    required: false
    default: 'bd-class-check,automated'

outputs:
  has-changes:
    description: 'Whether any changes were made'
    value: ${{ steps.update.outputs.has_changes }}
  
  total-changes:
    description: 'Total number of class changes made'
    value: ${{ steps.summary.outputs.total_changes }}
  
  modified-files:
    description: 'Number of files modified'
    value: ${{ steps.summary.outputs.modified_files }}
  
  pr-number:
    description: 'Pull request number (if created)'
    value: ${{ steps.create-pr.outputs.pull-request-number }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        echo "📦 Installing dependencies..."
        
        if [ ! -d "node_modules" ] || [ ! -f "node_modules/glob/package.json" ]; then
          npm ci
          echo "✓ Dependencies installed"
        else
          echo "✓ Dependencies already present"
        fi
    
    - name: Get Changes.txt commit date
      id: changes_date
      shell: bash
      run: |
        CHANGES_URL="${{ inputs.changes-url }}"
        
        # Get the commit date from GitHub API
        COMMIT_DATE=$(curl -s "https://api.github.com/repos/SyndiShanX/Update-Classes/commits?path=Changes.txt&sha=main&per_page=1" | jq -r '.[0].commit.committer.date')
        echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
        echo "Changes.txt last updated: $COMMIT_DATE"

    - name: Check if PR branch exists
      id: check_branch
      shell: bash
      run: |
        BRANCH="${{ inputs.branch-name }}"
        if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Run CSS class update script
      id: update
      shell: bash
      run: |
        export CHANGES_URL="${{ inputs.changes-url }}"
        export FILES_INPUT="${{ inputs.files }}"
        
        BRANCH="${{ inputs.branch-name }}"
        
        # Fetch branch if it exists
        if [[ "${{ steps.check_branch.outputs.exists }}" == "true" ]]; then
          echo "🔎 Existing branch found — fetching it"
          git fetch origin "$BRANCH"
          BASE_REF="origin/$BRANCH"
        else
          echo "🆕 No branch found — comparing against main"
          git fetch origin main
          BASE_REF="origin/main"
        fi
        
        echo "🔄 Running CSS class update..."
        node ${{ github.action_path }}/update-classes.js
        
        # Now check if anything actually changed
        echo "📌 Checking if changes differ from $BASE_REF"
        if git diff --quiet $BASE_REF -- .; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "✓ No changes since last PR — skipping"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "✨ Changes detected"
        fi

    - name: Read summary
      id: summary
      if: steps.update.outputs.has_changes == 'true'
      shell: bash
      run: |
        TOTAL=$(jq -r '.totalChanges' changes-summary.json)
        FILES=$(jq -r '.modifiedFiles | length' changes-summary.json)
        echo "total_changes=$TOTAL" >> $GITHUB_OUTPUT
        echo "modified_files=$FILES" >> $GITHUB_OUTPUT
    
    - name: Generate PR body
      if: steps.update.outputs.has_changes == 'true'
      shell: bash
      run: |
        COMMIT_DATE="${{ steps.changes_date.outputs.commit_date }}"
        
        cat << 'EOF' > pr-body.md
        ## CSS Class Updates
        
        This PR updates CSS classes based on changes from the upstream [SyndiShanX/Update-Classes](https://github.com/SyndiShanX/Update-Classes) `Changes.txt` file.
        
        **Changes.txt last updated:** COMMIT_DATE_PLACEHOLDER
        
        ### Summary
        EOF
        
        sed -i "s/COMMIT_DATE_PLACEHOLDER/$COMMIT_DATE/" pr-body.md
        
        # Add summary from JSON
        node -e "
          const summary = require('./changes-summary.json');
          console.log(\`\n**Total changes:** \${summary.totalChanges}\`);
          console.log(\`**Files modified:** \${summary.modifiedFiles.length}\n\`);
          console.log(\`### Modified Files\n\`);
          summary.modifiedFiles.forEach(file => console.log(\`- \${file}\`));
          console.log(\`\n### Changes Detail\n\`);
          const grouped = {};
          summary.changes.forEach(change => {
            if (!grouped[change.file]) grouped[change.file] = [];
            grouped[change.file].push(change);
          });
          Object.entries(grouped).forEach(([file, changes]) => {
            console.log(\`\n#### \${file}\n\`);
            changes.slice(0, 50).forEach(change => {
              console.log(\`- Line \${change.line}: \\\`.\${change.oldClass}\\\` → \\\`.\${change.newClass}\\\`\`);
            });
            if (changes.length > 50) {
              console.log(\`\n_... and \${changes.length - 50} more changes_\`);
            }
          });
        " >> pr-body.md
    
    - name: Create Pull Request
      id: create-pr
      if: steps.update.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.github-token }}
        commit-message: |
          ${{ inputs.commit-message }}
          
          Changes based on updates from ${{ steps.changes_date.outputs.commit_date }}
        branch: ${{ inputs.branch-name }}
        delete-branch: true
        title: ${{ inputs.pr-title }}
        body-path: pr-body.md
        labels: ${{ inputs.pr-labels }}
